
import os
from supabase import create_client, Client
from dotenv import load_dotenv

load_dotenv()

url = os.environ.get("SUPABASE_URL")
key = os.environ.get("SUPABASE_KEY")

if not url or not key:
    print("❌ Error: Missing Supabase credentials in .env")
    exit(1)

print(f"🔌 Connecting to Supabase: {url}")
supabase: Client = create_client(url, key)

# SQL for creating tables (Postgres syntax)
# Note: SQLite syntax in schema.sql might differ slightly (e.g. AUTOINCREMENT vs SERIAL in Postgres)
# But here we are using Supabase (Postgres).
# We'll use a direct query execution if possible, or usually we should create these in the dashboard.
# Since the supabase-py client doesn't support 'execute_sql' on the free tier directly without stored procedures usually,
# we might fail here if we try to run raw SQL.
# But let's try to run a simple check first.

print("⚠️ Note: Supabase Python client is for Data manipulation, not DDL (creating tables).")
print("ℹ️ Attempting to insert a test interaction to see if tables exist...")

try:
    # Just check if table exists by selecting
    response = supabase.table("users").select("count", count="exact").execute()
    print("✅ Connection successful! 'users' table found.")
except Exception as e:
    print(f"❌ Could not access 'users' table. Error: {e}")
    print("\n🚨 Action Required: You must create the tables in the Supabase Dashboard SQL Editor.")
    print("Use the following SQL:")
    print("-" * 50)
    print("""
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT PRIMARY KEY,
    username TEXT,
    first_name TEXT,
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    last_active TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id),
    role TEXT CHECK(role IN ('user', 'model')),
    content_text TEXT,
    content_audio_path TEXT,
    transcription TEXT,
    transcription_romanized TEXT,
    pronunciation_score INTEGER,
    feedback_text TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_interactions_user_created ON interactions(user_id, created_at DESC);
    """)
    print("-" * 50)
